// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: copyfrom.go

package repositories

import (
	"context"
)

// iteratorForInsertTodosByCellID implements pgx.CopyFromSource.
type iteratorForInsertTodosByCellID struct {
	rows                 []InsertTodosByCellIDParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertTodosByCellID) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertTodosByCellID) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].OwnerID,
		r.rows[0].CellID,
		r.rows[0].Content,
	}, nil
}

func (r iteratorForInsertTodosByCellID) Err() error {
	return nil
}

func (q *Queries) InsertTodosByCellID(ctx context.Context, arg []InsertTodosByCellIDParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"todos"}, []string{"owner_id", "cell_id", "content"}, &iteratorForInsertTodosByCellID{rows: arg})
}
