// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repositories

import (
	"mandalart.com/types"
)

type Cell struct {
	ID          int32           `json:"id"`
	SheetID     *int32          `json:"sheetId"`
	Goal        *string         `json:"goal"`
	Color       *string         `json:"color"`
	Step        int32           `json:"step"`
	Order       int32           `json:"order"`
	ParentID    *int32          `json:"parentId"`
	IsCompleted bool            `json:"isCompleted"`
	CreatedAt   types.Timestamp `json:"createdAt"`
	ModifiedAt  types.Timestamp `json:"modifiedAt"`
	OwnerID     *int32          `json:"ownerId"`
}

type Sheet struct {
	ID         int32           `json:"id"`
	OwnerID    *int32          `json:"ownerId"`
	Name       *string         `json:"name"`
	CreatedAt  types.Timestamp `json:"createdAt"`
	ModifiedAt types.Timestamp `json:"modifiedAt"`
}

type Todo struct {
	ID         int32           `json:"id"`
	OwnerID    *int32          `json:"ownerId"`
	CellID     *int32          `json:"cellId"`
	Content    *string         `json:"content"`
	CreatedAt  types.Timestamp `json:"createdAt"`
	ModifiedAt types.Timestamp `json:"modifiedAt"`
}

type User struct {
	ID             int32   `json:"id"`
	SocialID       *string `json:"socialId"`
	SocialProvider *string `json:"socialProvider"`
}
