// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repositories

import (
	"github.com/jackc/pgx/v5/pgtype"
	"mandalart.com/types"
)

type Cell struct {
	ID          int32           `json:"id"`
	SheetID     pgtype.Int4     `json:"sheetId"`
	Goal        pgtype.Text     `json:"goal"`
	Color       pgtype.Text     `json:"color"`
	Step        int32           `json:"step"`
	Order       int32           `json:"order"`
	ParentID    pgtype.Int4     `json:"parentId"`
	IsCompleted bool            `json:"isCompleted"`
	CreatedAt   types.Timestamp `json:"createdAt"`
	ModifiedAt  types.Timestamp `json:"modifiedAt"`
	OwnerID     pgtype.Int4     `json:"ownerId"`
}

type Sheet struct {
	ID         int32           `json:"id"`
	OwnerID    pgtype.Int4     `json:"ownerId"`
	Name       pgtype.Text     `json:"name"`
	CreatedAt  types.Timestamp `json:"createdAt"`
	ModifiedAt types.Timestamp `json:"modifiedAt"`
}

type Todo struct {
	ID         int32           `json:"id"`
	OwnerID    pgtype.Int4     `json:"ownerId"`
	CellID     pgtype.Int4     `json:"cellId"`
	Content    pgtype.Text     `json:"content"`
	CreatedAt  types.Timestamp `json:"createdAt"`
	ModifiedAt types.Timestamp `json:"modifiedAt"`
}

type User struct {
	ID             int32       `json:"id"`
	SocialID       pgtype.Text `json:"socialId"`
	SocialProvider pgtype.Text `json:"socialProvider"`
}
